apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: 
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/manifests
    repoURL: 'https://github.com/Lucas-Desouza/sample-app'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true